
name = "Dionyphany"
license = "MIT"
licenselink = "https://github.com/arkadianriver/dionyphany/blob/master/LICENSE"
description = "A portfolio and blog theme"
homepage = "https://github.com/arkadianriver/dionyphany"
demosite = "https://arkadianriver.github.io/dionyphany"
tags = ["blog", "portfolio"]
features = ["htmx", "filterable-skills"]

[author]
  name = "Gary Faircloth"
  homepage = "https://arkadianriver.com"

[original]
  name = "maewolff-portfolio-template"
  homepage = "https://astro.build/themes/details/maewolff-portfolio-template/"
  repo = "https://github.com/MaeWolff/astro-portfolio-template"
